import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FloatingBoxes from "@/componets/FloatingBoxes"; // <-- New client component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  h-full w-full flex flex-col items-center  bg-gray-900"`}
      >
        <div
          className=" w-full h-full "
          style={{
            background:
              "linear-gradient(90deg, rgba(2, 0, 36, 1) 0%, rgba(0, 212, 255, 1) 100%)",
          }}
        >
          <FloatingBoxes /> 
          
    {children}
  </div>        
      </body>
    </html>
  );
}
